makecode
makecode -c mkc-elecfreakscutebot.json
cp ./built/mbdal-binary.hex ../assets/robothex/microcode-robot-elecfreaks-cutebot-for-microbit-v1.hex
cp ./built/mbcodal-binary.hex ../assets/robothex/microcode-robot-elecfreaks-cutebot-for-microbit-v2.hex
makecode -c mkc-elecfreakscutebotpro.json
cp ./built/mbdal-binary.hex ../assets/robothex/microcode-robot-elecfreaks-cutebotpro-for-microbit-v1.hex
cp ./built/mbcodal-binary.hex ../assets/robothex/microcode-robot-elecfreaks-cutebotpro-for-microbit-v2.hex
makecode -c mkc-yahboomtinybit.json
cp ./built/mbdal-binary.hex ../assets/robothex/microcode-robot-yahboom-tinybit-for-microbit-v1.hex
cp ./built/mbcodal-binary.hex ../assets/robothex/microcode-robot-yahboom-tinybit-for-microbit-v2.hex
makecode -c mkc-keystudiominismartrobot.json
cp ./built/mbdal-binary.hex ../assets/robothex/microcode-robot-keystudio-minismartrobot-for-microbit-v1.hex
cp ./built/mbcodal-binary.hex ../assets/robothex/microcode-robot-keystudio-minismartrobot-for-microbit-v2.hex
makecode -c mkc-dfrobotmaqueen.json
cp ./built/mbdal-binary.hex ../assets/robothex/microcode-robot-dfrobot-maqueen-for-microbit-v1.hex
cp ./built/mbcodal-binary.hex ../assets/robothex/microcode-robot-dfrobot-maqueen-for-microbit-v2.hex
makecode -c mkc-dfrobotmaqueenplusv2.json
cp ./built/mbdal-binary.hex ../assets/robothex/microcode-robot-dfrobot-maqueen-plus-for-microbit-v1.hex
cp ./built/mbcodal-binary.hex ../assets/robothex/microcode-robot-dfrobot-maqueen-plus-for-microbit-v2.hex
makecode -c mkc-kittenbotminilfr.json
cp ./built/mbdal-binary.hex ../assets/robothex/microcode-robot-kittenbot-minilfr-for-microbit-v1.hex
cp ./built/mbcodal-binary.hex ../assets/robothex/microcode-robot-kittenbot-minilfr-for-microbit-v2.hex
makecode -c mkc-kittenbotnanobit.json
cp ./built/mbdal-binary.hex ../assets/robothex/microcode-robot-kittenbot-nanobit-for-microbit-v1.hex
cp ./built/mbcodal-binary.hex ../assets/robothex/microcode-robot-kittenbot-nanobit-for-microbit-v2.hex
makecode -c mkc-kittenbotrobotbit.json
cp ./built/mbdal-binary.hex ../assets/robothex/microcode-robot-kittenbot-robotbit-for-microbit-v1.hex
cp ./built/mbcodal-binary.hex ../assets/robothex/microcode-robot-kittenbot-robotbit-for-microbit-v2.hex
makecode -c mkc-inksmithk8.json
cp ./built/mbdal-binary.hex ../assets/robothex/microcode-robot-inksmith-k8-for-microbit-v1.hex
cp ./built/mbcodal-binary.hex ../assets/robothex/microcode-robot-inksmith-k8-for-microbit-v2.hex
